### Exception Handling in Java:-

* Exception is an abnormal condition that interrupts the normal flow of the program terminate the program.
* if you want to develop a robust application then we have to handle the exception.
* In such cases we get a system generated error message. The good thing about exceptions is that they can be handled   	 in Java. By handling the exceptions we can provide a meaningful message to the user about the issue rather than a 
  system generated message, which may not be understandable to a user.

* if we not handled exception program execution gets terminated and a system generated error message is shown to the  	user.
* Exception handling ensures that the flow of the program doesnâ€™t break when an exception occur.
* Exception object created by the method in which the exception is occur.
* if you want to develop the custom exception then you have to create the exception object by using throw keyword
  then it will pass to the Jvm. we have to write the class of exception name and extends RuntimeException.
----------------------------------------------------------------------------------------------------------------------
                                               Throwable
                                                   '
 										 '
                                      -----------------------------------
                                      '                                  '                                   
                                      '                                  '
                                     Error                           Exception
                                                                         '
                                                                   ------'-------
                                                                   :             :
                                                               RuntimeException IOException  .
                                                                        :             :
                                                Arithmetic Exception.   :             '--1-File Not Found Exception.
                                  Array Index Out of Bounds Exception.  :             :--2-Class Not Found Exception.
----------------------------------------------------------------------------------------------------------------------
* There are two types of exceptions in Java:
  1)Checked exceptions-
   - Java forces you to handle these error scenarios in some manner in your application code.
   - FileNotFoundException is Chacked type exception.
   - Checked exceptions occur at compile time.
   - The compiler checks a checked exception.
   - They are the sub-class of the exception class.
   - Here, the JVM needs the exception to catch and handle.
   - File Not Found Exception.
   - Class Not Found Exception.

  2)Unchecked exceptions:-
   - Unchecked exceptions occur at runtime.
   - The compiler does not check these types of exceptions.
   - These types of exceptions cannot be a catch or handle at the time of compilation, because they get generated by
     the mistakes in the program.
   - They are runtime exceptions and hence are not a part of the Exception class.
   - Here, the JVM does not require the exception to catch and handle. 
   - Arithmetic Exception.
   - Null Pointer Exception.
   - Array Index Out of Bounds Exception.
----------------------------------------------------------------------------------------------------------------------
### Java try...catch block:-
   - The code that might generate an exception is placed in the try block.
   - Every try block should be immediately followed by the catch or finally block. 
   - catch blocks cannot be used alone and must always be preceded by a try block.
   - For each try block, there can be only one finally block.
   - The finally block is optional. However, if defined, it is always executed (even if the exception doesn't occur).
   - Having a finally block is considered a good practice. It is because it includes important cleanup code such as:
   - closing a file or connection.
   - Use of System.exit() method.
   - An exception occurs in the finally block.
   - The death of a thread.
   - When an exception occurs, the runtime system skips the rest of the code in the try block.
----------------------------------------------------------------------------------------------------------------------
### Throw keyword and Throws keyword :-
### Throw keyword:-
   - if you want to develop your own (custom) exception.
   - by using Throw keyword we can create our own exception.
   - throw new TooOldException("age must be less than 60");
   - here we create the TooOldException then object will pass to the JVM.
   - most of the time use in the Unchecked Exception(Runtime Exception).
   - after throw dont write anything.
   - we have to define the class that class is extends RuntimeException.
----------------------------------------------------------------------------------------------------------------------
### Thow keyword example:-

		class TooYoungException extends RuntimeException
		{
			TooYoungException()
			{
				System.out.println("for marrange age must be grater than 18  ");
			}
		}
		

		public class Test
		{
			public static void main(String str[])
			{
				Scanner sc=new Scanner(System.in);
				System.out.println("Enter the age ");
				int age=sc.nextInt();
				if(age<18)
				{
					try 
					{
						throw new TooYoungException();
					} 
					catch (TooYoungException e) 
					{
						System.out.println("inside the catch block");
					
					} 
                }
				
				else
				{
					System.out.println(" welcome to shadi.com ");
				}
				System.out.println("this will show that program will not terminate");
			}
		}
----------------------------------------------------------------------------------------------------------------------
### Throws keyword- 
 * exception occur in method then we have to handle it by using try and catch block.
 * if you dont want to handle the exception in that method then we can use the Thow keyword.
 * void readMethod() throws FileNotFoundException.
 * by using Throw keyword we can suppress the exception but we have to handle it in the method where we want to 
 * use it we want to use in main method so we have to write try catch block in there.

---------------------------------------------------------------------------------------------------------------------
### Throws keyword example :-
package m;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.*;

class Read
{
	void readMethod() throws FileNotFoundException
	{
		 FileInputStream fin=new FileInputStream("D:\\testout.txt");
	}
	void fun()
	{
		System.out.println("program will not terminated");
	}
}
	public class Test
	{
		public static void main(String str[])
		{
			Read read=new Read();
			try 
			{
				read.readMethod();
			}
			catch (FileNotFoundException e) 
			{
			  System.out.println("file not found cheack filename/filepath");
			}
			read.fun();
		}
	}
--------------------------------------------------------------------------------------------------------------------
